# networks:
#   olivia-project-network:
#     name: olivia-project-network
# volumes:
#   mongo_data:
#   mongo_configdb:

services:
  # this service should use the web image after you build it
  nextjs-prod:
    container_name: nextjs-prod
    build:
      context: .
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - 3000:3000
    # networks:
    #   - olivia-project-network
    # depends_on:
    #   - db
  # db:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   volumes:
  #     - mongo_data:/data/db
  #     - mongo_configdb:/data/configdb
  #   expose:
  #     - "27017"
  #   networks:
  #     - olivia-project-network
  # nginx:
  #   image: nginx
  #   volumes:
  #   - ./nginx.conf:/etc/nginx/nginx.conf
  #   - /etc/letsencrypt/live/zamanfu.fun/fullchain.pem:/etc/nginx/ssl/fullchain.pem
  #   - /etc/letsencrypt/live/zamanfu.fun/privkey.pem:/etc/nginx/ssl/privkey.pem
  #   ports:
  #   - "3000:3000"
  #   depends_on:
  #     - nextjs
  # this service is the database service using mongo from docker hub
